name: Godot Ollama API Script File Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1
          export-templates: false

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Start serving
        run: |
            ollama serve &
            ollama pull gemma3
            sleep 5
            time curl -i http://localhost:11434

      - name: Run test files
        run: |
          godot --headless --no-header --script examples/blob_example.gd
          godot --headless --no-header --script examples/fetch_info_example.gd
          godot --headless --no-header --script examples/list_example.gd
          godot --headless --no-header --script examples/prompt_example.gd
          godot --headless --no-header --script examples/runner_version_example.gd
