name: Godot Headless Script Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1
          export-templates: false

      - name: Run test files
        run: |
          godot --headless --script test/net_util_test.gd
          godot --headless --script test/sha256_validator_test.gd
